version: '3.7'

services:
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    container_name: drama-minio
    volumes:
      - ./volumes/minio/data:/data
    environment:
      MINIO_ACCESS_KEY: drama
      MINIO_SECRET_KEY: minioS3Cre1K3y
    ports:
      - "9000:9000"
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
  rabbit:
    image: rabbitmq:3-management
    container_name: drama-mq
    environment:
      RABBITMQ_DEFAULT_USER: drama
      RABBITMQ_DEFAULT_PASS: rabbit
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
  mongo:
    image: mongo:4.2.0-bionic
    container_name: drama-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: drama
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mongo/db/:/data/db
    restart: always